
SELECT
 DT.PLANT_CD
,DT.PARENT_SEC_CD
,DT.SOURCE_CD
,DT.SOURCE_NAME
,DT.ITEM_CD
,DT.ITEM_NAME
,DT.MODEL
,DT.SNP
,DT.LCT
,IFNULL(SUM( DT.DM_01_1 ),0)  DM_01_1
,IFNULL(SUM( DT.DM_02_1 ),0)  DM_02_1
,IFNULL(SUM( DT.DM_03_1 ),0)  DM_03_1
,IFNULL(SUM( DT.DM_04_1 ),0)  DM_04_1
,IFNULL(SUM( DT.DM_05_1 ),0)  DM_05_1
,IFNULL(SUM( DT.DM_06_1 ),0)  DM_06_1
,IFNULL(SUM( DT.DM_07_1 ),0)  DM_07_1
,IFNULL(SUM( DT.DM_08_1 ),0)  DM_08_1
,IFNULL(SUM( DT.DM_09_1 ),0)  DM_09_1
,IFNULL(SUM( DT.DM_10_1 ),0)  DM_10_1
,IFNULL(SUM( DT.DM_11_1 ),0)  DM_11_1
,IFNULL(SUM( DT.DM_12_1 ),0)  DM_12_1
,IFNULL(SUM( DT.DM_13_1 ),0)  DM_13_1
,IFNULL(SUM( DT.DM_14_1 ),0)  DM_14_1
,IFNULL(SUM( DT.DM_15_1 ),0)  DM_15_1
,IFNULL(SUM( DT.DM_16_1 ),0)  DM_16_1
,IFNULL(SUM( DT.DM_17_1 ),0)  DM_17_1
,IFNULL(SUM( DT.DM_18_1 ),0)  DM_18_1
,IFNULL(SUM( DT.DM_19_1 ),0)  DM_19_1
,IFNULL(SUM( DT.DM_20_1 ),0)  DM_20_1
,IFNULL(SUM( DT.DM_21_1 ),0)  DM_21_1
,IFNULL(SUM( DT.DM_22_1 ),0)  DM_22_1
,IFNULL(SUM( DT.DM_23_1 ),0)  DM_23_1
,IFNULL(SUM( DT.DM_24_1 ),0)  DM_24_1
,IFNULL(SUM( DT.DM_25_1 ),0)  DM_25_1
,IFNULL(SUM( DT.DM_26_1 ),0)  DM_26_1
,IFNULL(SUM( DT.DM_27_1 ),0)  DM_27_1
,IFNULL(SUM( DT.DM_28_1 ),0)  DM_28_1
,IFNULL(SUM( DT.DM_29_1 ),0)  DM_29_1
,IFNULL(SUM( DT.DM_30_1 ),0)  DM_30_1
,IFNULL(SUM( DT.DM_31_1 ),0)  DM_31_1

,IFNULL(SUM( DT.DM_01_2 ),0)  DM_01_2
,IFNULL(SUM( DT.DM_02_2 ),0)  DM_02_2
,IFNULL(SUM( DT.DM_03_2 ),0)  DM_03_2
,IFNULL(SUM( DT.DM_04_2 ),0)  DM_04_2
,IFNULL(SUM( DT.DM_05_2 ),0)  DM_05_2
,IFNULL(SUM( DT.DM_06_2 ),0)  DM_06_2
,IFNULL(SUM( DT.DM_07_2 ),0)  DM_07_2
,IFNULL(SUM( DT.DM_08_2 ),0)  DM_08_2
,IFNULL(SUM( DT.DM_09_2 ),0)  DM_09_2
,IFNULL(SUM( DT.DM_10_2 ),0)  DM_10_2
,IFNULL(SUM( DT.DM_11_2 ),0)  DM_11_2
,IFNULL(SUM( DT.DM_12_2 ),0)  DM_12_2
,IFNULL(SUM( DT.DM_13_2 ),0)  DM_13_2
,IFNULL(SUM( DT.DM_14_2 ),0)  DM_14_2
,IFNULL(SUM( DT.DM_15_2 ),0)  DM_15_2
,IFNULL(SUM( DT.DM_16_2 ),0)  DM_16_2
,IFNULL(SUM( DT.DM_17_2 ),0)  DM_17_2
,IFNULL(SUM( DT.DM_18_2 ),0)  DM_18_2
,IFNULL(SUM( DT.DM_19_2 ),0)  DM_19_2
,IFNULL(SUM( DT.DM_20_2 ),0)  DM_20_2
,IFNULL(SUM( DT.DM_21_2 ),0)  DM_21_2
,IFNULL(SUM( DT.DM_22_2 ),0)  DM_22_2
,IFNULL(SUM( DT.DM_23_2 ),0)  DM_23_2
,IFNULL(SUM( DT.DM_24_2 ),0)  DM_24_2
,IFNULL(SUM( DT.DM_25_2 ),0)  DM_25_2
,IFNULL(SUM( DT.DM_26_2 ),0)  DM_26_2
,IFNULL(SUM( DT.DM_27_2 ),0)  DM_27_2
,IFNULL(SUM( DT.DM_28_2 ),0)  DM_28_2
,IFNULL(SUM( DT.DM_29_2 ),0)  DM_29_2
,IFNULL(SUM( DT.DM_30_2 ),0)  DM_30_2
,IFNULL(SUM( DT.DM_31_2 ),0)  DM_31_2

,IFNULL(SUM( DT.DM_01_3 ),0)  DM_01_3
,IFNULL(SUM( DT.DM_02_3 ),0)  DM_02_3
,IFNULL(SUM( DT.DM_03_3 ),0)  DM_03_3
,IFNULL(SUM( DT.DM_04_3 ),0)  DM_04_3
,IFNULL(SUM( DT.DM_05_3 ),0)  DM_05_3
,IFNULL(SUM( DT.DM_06_3 ),0)  DM_06_3
,IFNULL(SUM( DT.DM_07_3 ),0)  DM_07_3
,IFNULL(SUM( DT.DM_08_3 ),0)  DM_08_3
,IFNULL(SUM( DT.DM_09_3 ),0)  DM_09_3
,IFNULL(SUM( DT.DM_10_3 ),0)  DM_10_3
,IFNULL(SUM( DT.DM_11_3 ),0)  DM_11_3
,IFNULL(SUM( DT.DM_12_3 ),0)  DM_12_3
,IFNULL(SUM( DT.DM_13_3 ),0)  DM_13_3
,IFNULL(SUM( DT.DM_14_3 ),0)  DM_14_3
,IFNULL(SUM( DT.DM_15_3 ),0)  DM_15_3
,IFNULL(SUM( DT.DM_16_3 ),0)  DM_16_3
,IFNULL(SUM( DT.DM_17_3 ),0)  DM_17_3
,IFNULL(SUM( DT.DM_18_3 ),0)  DM_18_3
,IFNULL(SUM( DT.DM_19_3 ),0)  DM_19_3
,IFNULL(SUM( DT.DM_20_3 ),0)  DM_20_3
,IFNULL(SUM( DT.DM_21_3 ),0)  DM_21_3
,IFNULL(SUM( DT.DM_22_3 ),0)  DM_22_3
,IFNULL(SUM( DT.DM_23_3 ),0)  DM_23_3
,IFNULL(SUM( DT.DM_24_3 ),0)  DM_24_3
,IFNULL(SUM( DT.DM_25_3 ),0)  DM_25_3
,IFNULL(SUM( DT.DM_26_3 ),0)  DM_26_3
,IFNULL(SUM( DT.DM_27_3 ),0)  DM_27_3
,IFNULL(SUM( DT.DM_28_3 ),0)  DM_28_3
,IFNULL(SUM( DT.DM_29_3 ),0)  DM_29_3
,IFNULL(SUM( DT.DM_30_3 ),0)  DM_30_3
,IFNULL(SUM( DT.DM_31_3 ),0)  DM_31_3

,IFNULL(SUM( DT.PL_01_1 ),0)  PL_01_1
,IFNULL(SUM( DT.PL_02_1 ),0)  PL_02_1
,IFNULL(SUM( DT.PL_03_1 ),0)  PL_03_1
,IFNULL(SUM( DT.PL_04_1 ),0)  PL_04_1
,IFNULL(SUM( DT.PL_05_1 ),0)  PL_05_1
,IFNULL(SUM( DT.PL_06_1 ),0)  PL_06_1
,IFNULL(SUM( DT.PL_07_1 ),0)  PL_07_1
,IFNULL(SUM( DT.PL_08_1 ),0)  PL_08_1
,IFNULL(SUM( DT.PL_09_1 ),0)  PL_09_1
,IFNULL(SUM( DT.PL_10_1 ),0)  PL_10_1
,IFNULL(SUM( DT.PL_11_1 ),0)  PL_11_1
,IFNULL(SUM( DT.PL_12_1 ),0)  PL_12_1
,IFNULL(SUM( DT.PL_13_1 ),0)  PL_13_1
,IFNULL(SUM( DT.PL_14_1 ),0)  PL_14_1
,IFNULL(SUM( DT.PL_15_1 ),0)  PL_15_1
,IFNULL(SUM( DT.PL_16_1 ),0)  PL_16_1
,IFNULL(SUM( DT.PL_17_1 ),0)  PL_17_1
,IFNULL(SUM( DT.PL_18_1 ),0)  PL_18_1
,IFNULL(SUM( DT.PL_19_1 ),0)  PL_19_1
,IFNULL(SUM( DT.PL_20_1 ),0)  PL_20_1
,IFNULL(SUM( DT.PL_21_1 ),0)  PL_21_1
,IFNULL(SUM( DT.PL_22_1 ),0)  PL_22_1
,IFNULL(SUM( DT.PL_23_1 ),0)  PL_23_1
,IFNULL(SUM( DT.PL_24_1 ),0)  PL_24_1
,IFNULL(SUM( DT.PL_25_1 ),0)  PL_25_1
,IFNULL(SUM( DT.PL_26_1 ),0)  PL_26_1
,IFNULL(SUM( DT.PL_27_1 ),0)  PL_27_1
,IFNULL(SUM( DT.PL_28_1 ),0)  PL_28_1
,IFNULL(SUM( DT.PL_29_1 ),0)  PL_29_1
,IFNULL(SUM( DT.PL_30_1 ),0)  PL_30_1
,IFNULL(SUM( DT.PL_31_1 ),0)  PL_31_1

,IFNULL(SUM( DT.PL_01_2 ),0)  PL_01_2
,IFNULL(SUM( DT.PL_02_2 ),0)  PL_02_2
,IFNULL(SUM( DT.PL_03_2 ),0)  PL_03_2
,IFNULL(SUM( DT.PL_04_2 ),0)  PL_04_2
,IFNULL(SUM( DT.PL_05_2 ),0)  PL_05_2
,IFNULL(SUM( DT.PL_06_2 ),0)  PL_06_2
,IFNULL(SUM( DT.PL_07_2 ),0)  PL_07_2
,IFNULL(SUM( DT.PL_08_2 ),0)  PL_08_2
,IFNULL(SUM( DT.PL_09_2 ),0)  PL_09_2
,IFNULL(SUM( DT.PL_10_2 ),0)  PL_10_2
,IFNULL(SUM( DT.PL_11_2 ),0)  PL_11_2
,IFNULL(SUM( DT.PL_12_2 ),0)  PL_12_2
,IFNULL(SUM( DT.PL_13_2 ),0)  PL_13_2
,IFNULL(SUM( DT.PL_14_2 ),0)  PL_14_2
,IFNULL(SUM( DT.PL_15_2 ),0)  PL_15_2
,IFNULL(SUM( DT.PL_16_2 ),0)  PL_16_2
,IFNULL(SUM( DT.PL_17_2 ),0)  PL_17_2
,IFNULL(SUM( DT.PL_18_2 ),0)  PL_18_2
,IFNULL(SUM( DT.PL_19_2 ),0)  PL_19_2
,IFNULL(SUM( DT.PL_20_2 ),0)  PL_20_2
,IFNULL(SUM( DT.PL_21_2 ),0)  PL_21_2
,IFNULL(SUM( DT.PL_22_2 ),0)  PL_22_2
,IFNULL(SUM( DT.PL_23_2 ),0)  PL_23_2
,IFNULL(SUM( DT.PL_24_2 ),0)  PL_24_2
,IFNULL(SUM( DT.PL_25_2 ),0)  PL_25_2
,IFNULL(SUM( DT.PL_26_2 ),0)  PL_26_2
,IFNULL(SUM( DT.PL_27_2 ),0)  PL_27_2
,IFNULL(SUM( DT.PL_28_2 ),0)  PL_28_2
,IFNULL(SUM( DT.PL_29_2 ),0)  PL_29_2
,IFNULL(SUM( DT.PL_30_2 ),0)  PL_30_2
,IFNULL(SUM( DT.PL_31_2 ),0)  PL_31_2

,IFNULL(SUM( DT.PL_01_3 ),0)  PL_01_3
,IFNULL(SUM( DT.PL_02_3 ),0)  PL_02_3
,IFNULL(SUM( DT.PL_03_3 ),0)  PL_03_3
,IFNULL(SUM( DT.PL_04_3 ),0)  PL_04_3
,IFNULL(SUM( DT.PL_05_3 ),0)  PL_05_3
,IFNULL(SUM( DT.PL_06_3 ),0)  PL_06_3
,IFNULL(SUM( DT.PL_07_3 ),0)  PL_07_3
,IFNULL(SUM( DT.PL_08_3 ),0)  PL_08_3
,IFNULL(SUM( DT.PL_09_3 ),0)  PL_09_3
,IFNULL(SUM( DT.PL_10_3 ),0)  PL_10_3
,IFNULL(SUM( DT.PL_11_3 ),0)  PL_11_3
,IFNULL(SUM( DT.PL_12_3 ),0)  PL_12_3
,IFNULL(SUM( DT.PL_13_3 ),0)  PL_13_3
,IFNULL(SUM( DT.PL_14_3 ),0)  PL_14_3
,IFNULL(SUM( DT.PL_15_3 ),0)  PL_15_3
,IFNULL(SUM( DT.PL_16_3 ),0)  PL_16_3
,IFNULL(SUM( DT.PL_17_3 ),0)  PL_17_3
,IFNULL(SUM( DT.PL_18_3 ),0)  PL_18_3
,IFNULL(SUM( DT.PL_19_3 ),0)  PL_19_3
,IFNULL(SUM( DT.PL_20_3 ),0)  PL_20_3
,IFNULL(SUM( DT.PL_21_3 ),0)  PL_21_3
,IFNULL(SUM( DT.PL_22_3 ),0)  PL_22_3
,IFNULL(SUM( DT.PL_23_3 ),0)  PL_23_3
,IFNULL(SUM( DT.PL_24_3 ),0)  PL_24_3
,IFNULL(SUM( DT.PL_25_3 ),0)  PL_25_3
,IFNULL(SUM( DT.PL_26_3 ),0)  PL_26_3
,IFNULL(SUM( DT.PL_27_3 ),0)  PL_27_3
,IFNULL(SUM( DT.PL_28_3 ),0)  PL_28_3
,IFNULL(SUM( DT.PL_29_3 ),0)  PL_29_3
,IFNULL(SUM( DT.PL_30_3 ),0)  PL_30_3
,IFNULL(SUM( DT.PL_31_3 ),0)  PL_31_3

,IFNULL(SUM( DT.AC_01_1 ),0)  AC_01_1
,IFNULL(SUM( DT.AC_02_1 ),0)  AC_02_1
,IFNULL(SUM( DT.AC_03_1 ),0)  AC_03_1
,IFNULL(SUM( DT.AC_04_1 ),0)  AC_04_1
,IFNULL(SUM( DT.AC_05_1 ),0)  AC_05_1
,IFNULL(SUM( DT.AC_06_1 ),0)  AC_06_1
,IFNULL(SUM( DT.AC_07_1 ),0)  AC_07_1
,IFNULL(SUM( DT.AC_08_1 ),0)  AC_08_1
,IFNULL(SUM( DT.AC_09_1 ),0)  AC_09_1
,IFNULL(SUM( DT.AC_10_1 ),0)  AC_10_1
,IFNULL(SUM( DT.AC_11_1 ),0)  AC_11_1
,IFNULL(SUM( DT.AC_12_1 ),0)  AC_12_1
,IFNULL(SUM( DT.AC_13_1 ),0)  AC_13_1
,IFNULL(SUM( DT.AC_14_1 ),0)  AC_14_1
,IFNULL(SUM( DT.AC_15_1 ),0)  AC_15_1
,IFNULL(SUM( DT.AC_16_1 ),0)  AC_16_1
,IFNULL(SUM( DT.AC_17_1 ),0)  AC_17_1
,IFNULL(SUM( DT.AC_18_1 ),0)  AC_18_1
,IFNULL(SUM( DT.AC_19_1 ),0)  AC_19_1
,IFNULL(SUM( DT.AC_20_1 ),0)  AC_20_1
,IFNULL(SUM( DT.AC_21_1 ),0)  AC_21_1
,IFNULL(SUM( DT.AC_22_1 ),0)  AC_22_1
,IFNULL(SUM( DT.AC_23_1 ),0)  AC_23_1
,IFNULL(SUM( DT.AC_24_1 ),0)  AC_24_1
,IFNULL(SUM( DT.AC_25_1 ),0)  AC_25_1
,IFNULL(SUM( DT.AC_26_1 ),0)  AC_26_1
,IFNULL(SUM( DT.AC_27_1 ),0)  AC_27_1
,IFNULL(SUM( DT.AC_28_1 ),0)  AC_28_1
,IFNULL(SUM( DT.AC_29_1 ),0)  AC_29_1
,IFNULL(SUM( DT.AC_30_1 ),0)  AC_30_1
,IFNULL(SUM( DT.AC_31_1 ),0)  AC_31_1

,IFNULL(SUM( DT.AC_01_2 ),0)  AC_01_2
,IFNULL(SUM( DT.AC_02_2 ),0)  AC_02_2
,IFNULL(SUM( DT.AC_03_2 ),0)  AC_03_2
,IFNULL(SUM( DT.AC_04_2 ),0)  AC_04_2
,IFNULL(SUM( DT.AC_05_2 ),0)  AC_05_2
,IFNULL(SUM( DT.AC_06_2 ),0)  AC_06_2
,IFNULL(SUM( DT.AC_07_2 ),0)  AC_07_2
,IFNULL(SUM( DT.AC_08_2 ),0)  AC_08_2
,IFNULL(SUM( DT.AC_09_2 ),0)  AC_09_2
,IFNULL(SUM( DT.AC_10_2 ),0)  AC_10_2
,IFNULL(SUM( DT.AC_11_2 ),0)  AC_11_2
,IFNULL(SUM( DT.AC_12_2 ),0)  AC_12_2
,IFNULL(SUM( DT.AC_13_2 ),0)  AC_13_2
,IFNULL(SUM( DT.AC_14_2 ),0)  AC_14_2
,IFNULL(SUM( DT.AC_15_2 ),0)  AC_15_2
,IFNULL(SUM( DT.AC_16_2 ),0)  AC_16_2
,IFNULL(SUM( DT.AC_17_2 ),0)  AC_17_2
,IFNULL(SUM( DT.AC_18_2 ),0)  AC_18_2
,IFNULL(SUM( DT.AC_19_2 ),0)  AC_19_2
,IFNULL(SUM( DT.AC_20_2 ),0)  AC_20_2
,IFNULL(SUM( DT.AC_21_2 ),0)  AC_21_2
,IFNULL(SUM( DT.AC_22_2 ),0)  AC_22_2
,IFNULL(SUM( DT.AC_23_2 ),0)  AC_23_2
,IFNULL(SUM( DT.AC_24_2 ),0)  AC_24_2
,IFNULL(SUM( DT.AC_25_2 ),0)  AC_25_2
,IFNULL(SUM( DT.AC_26_2 ),0)  AC_26_2
,IFNULL(SUM( DT.AC_27_2 ),0)  AC_27_2
,IFNULL(SUM( DT.AC_28_2 ),0)  AC_28_2
,IFNULL(SUM( DT.AC_29_2 ),0)  AC_29_2
,IFNULL(SUM( DT.AC_30_2 ),0)  AC_30_2
,IFNULL(SUM( DT.AC_31_2 ),0)  AC_31_2

,IFNULL(SUM( DT.AC_01_3 ),0)  AC_01_3
,IFNULL(SUM( DT.AC_02_3 ),0)  AC_02_3
,IFNULL(SUM( DT.AC_03_3 ),0)  AC_03_3
,IFNULL(SUM( DT.AC_04_3 ),0)  AC_04_3
,IFNULL(SUM( DT.AC_05_3 ),0)  AC_05_3
,IFNULL(SUM( DT.AC_06_3 ),0)  AC_06_3
,IFNULL(SUM( DT.AC_07_3 ),0)  AC_07_3
,IFNULL(SUM( DT.AC_08_3 ),0)  AC_08_3
,IFNULL(SUM( DT.AC_09_3 ),0)  AC_09_3
,IFNULL(SUM( DT.AC_10_3 ),0)  AC_10_3
,IFNULL(SUM( DT.AC_11_3 ),0)  AC_11_3
,IFNULL(SUM( DT.AC_12_3 ),0)  AC_12_3
,IFNULL(SUM( DT.AC_13_3 ),0)  AC_13_3
,IFNULL(SUM( DT.AC_14_3 ),0)  AC_14_3
,IFNULL(SUM( DT.AC_15_3 ),0)  AC_15_3
,IFNULL(SUM( DT.AC_16_3 ),0)  AC_16_3
,IFNULL(SUM( DT.AC_17_3 ),0)  AC_17_3
,IFNULL(SUM( DT.AC_18_3 ),0)  AC_18_3
,IFNULL(SUM( DT.AC_19_3 ),0)  AC_19_3
,IFNULL(SUM( DT.AC_20_3 ),0)  AC_20_3
,IFNULL(SUM( DT.AC_21_3 ),0)  AC_21_3
,IFNULL(SUM( DT.AC_22_3 ),0)  AC_22_3
,IFNULL(SUM( DT.AC_23_3 ),0)  AC_23_3
,IFNULL(SUM( DT.AC_24_3 ),0)  AC_24_3
,IFNULL(SUM( DT.AC_25_3 ),0)  AC_25_3
,IFNULL(SUM( DT.AC_26_3 ),0)  AC_26_3
,IFNULL(SUM( DT.AC_27_3 ),0)  AC_27_3
,IFNULL(SUM( DT.AC_28_3 ),0)  AC_28_3
,IFNULL(SUM( DT.AC_29_3 ),0)  AC_29_3
,IFNULL(SUM( DT.AC_30_3 ),0)  AC_30_3
,IFNULL(SUM( DT.AC_31_3 ),0)  AC_31_3

FROM
(
SELECT

 DT.PLANT_CD
,DT.PARENT_SEC_CD
,DT.SOURCE_CD
,DT.SOURCE_NAME
,DT.ITEM_CD
,DT.ITEM_NAME
,DT.MODEL
,DT.SNP
,DT.LCT
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 1 MONTH ) + INTERVAL 1 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_01_1
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 1 MONTH ) + INTERVAL 2 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_02_1
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 1 MONTH ) + INTERVAL 3 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_03_1
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 1 MONTH ) + INTERVAL 4 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_04_1
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 1 MONTH ) + INTERVAL 5 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_05_1
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 1 MONTH ) + INTERVAL 6 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_06_1
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 1 MONTH ) + INTERVAL 7 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_07_1
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 1 MONTH ) + INTERVAL 8 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_08_1
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 1 MONTH ) + INTERVAL 9 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_09_1
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 1 MONTH ) + INTERVAL 10 DAY , '%Y-%m-%d') AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_10_1
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 1 MONTH ) + INTERVAL 11 DAY , '%Y-%m-%d') AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_11_1
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 1 MONTH ) + INTERVAL 12 DAY , '%Y-%m-%d') AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_12_1
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 1 MONTH ) + INTERVAL 13 DAY , '%Y-%m-%d') AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_13_1
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 1 MONTH ) + INTERVAL 14 DAY , '%Y-%m-%d') AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_14_1
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 1 MONTH ) + INTERVAL 15 DAY , '%Y-%m-%d') AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_15_1
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 1 MONTH ) + INTERVAL 16 DAY , '%Y-%m-%d') AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_16_1
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 1 MONTH ) + INTERVAL 17 DAY , '%Y-%m-%d') AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_17_1
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 1 MONTH ) + INTERVAL 18 DAY , '%Y-%m-%d') AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_18_1
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 1 MONTH ) + INTERVAL 19 DAY , '%Y-%m-%d') AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_19_1
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 1 MONTH ) + INTERVAL 20 DAY , '%Y-%m-%d') AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_20_1
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 1 MONTH ) + INTERVAL 21 DAY , '%Y-%m-%d') AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_21_1
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 1 MONTH ) + INTERVAL 22 DAY , '%Y-%m-%d') AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_22_1
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 1 MONTH ) + INTERVAL 23 DAY , '%Y-%m-%d') AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_23_1
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 1 MONTH ) + INTERVAL 24 DAY , '%Y-%m-%d') AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_24_1
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 1 MONTH ) + INTERVAL 25 DAY , '%Y-%m-%d') AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_25_1
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 1 MONTH ) + INTERVAL 26 DAY , '%Y-%m-%d') AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_26_1
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 1 MONTH ) + INTERVAL 27 DAY , '%Y-%m-%d') AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_27_1
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 1 MONTH ) + INTERVAL 28 DAY , '%Y-%m-%d') AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_28_1
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 1 MONTH ) + INTERVAL 29 DAY , '%Y-%m-%d') AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_29_1
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 1 MONTH ) + INTERVAL 30 DAY , '%Y-%m-%d') AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_30_1
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 1 MONTH ) + INTERVAL 31 DAY , '%Y-%m-%d') AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_31_1


,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 0 MONTH ) + INTERVAL 1 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_01_2
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 0 MONTH ) + INTERVAL 2 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_02_2
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 0 MONTH ) + INTERVAL 3 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_03_2
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 0 MONTH ) + INTERVAL 4 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_04_2
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 0 MONTH ) + INTERVAL 5 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_05_2
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 0 MONTH ) + INTERVAL 6 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_06_2
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 0 MONTH ) + INTERVAL 7 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_07_2
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 0 MONTH ) + INTERVAL 8 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_08_2
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 0 MONTH ) + INTERVAL 9 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_09_2
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 0 MONTH ) + INTERVAL 10 DAY , '%Y-%m-%d') AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_10_2
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 0 MONTH ) + INTERVAL 11 DAY , '%Y-%m-%d') AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_11_2
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 0 MONTH ) + INTERVAL 12 DAY , '%Y-%m-%d') AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_12_2
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 0 MONTH ) + INTERVAL 13 DAY , '%Y-%m-%d') AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_13_2
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 0 MONTH ) + INTERVAL 14 DAY , '%Y-%m-%d') AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_14_2
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 0 MONTH ) + INTERVAL 15 DAY , '%Y-%m-%d') AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_15_2
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 0 MONTH ) + INTERVAL 16 DAY , '%Y-%m-%d') AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_16_2
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 0 MONTH ) + INTERVAL 17 DAY , '%Y-%m-%d') AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_17_2
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 0 MONTH ) + INTERVAL 18 DAY , '%Y-%m-%d') AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_18_2
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 0 MONTH ) + INTERVAL 19 DAY , '%Y-%m-%d') AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_19_2
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 0 MONTH ) + INTERVAL 20 DAY , '%Y-%m-%d') AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_20_2
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 0 MONTH ) + INTERVAL 21 DAY , '%Y-%m-%d') AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_21_2
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 0 MONTH ) + INTERVAL 22 DAY , '%Y-%m-%d') AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_22_2
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 0 MONTH ) + INTERVAL 23 DAY , '%Y-%m-%d') AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_23_2
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 0 MONTH ) + INTERVAL 24 DAY , '%Y-%m-%d') AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_24_2
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 0 MONTH ) + INTERVAL 25 DAY , '%Y-%m-%d') AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_25_2
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 0 MONTH ) + INTERVAL 26 DAY , '%Y-%m-%d') AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_26_2
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 0 MONTH ) + INTERVAL 27 DAY , '%Y-%m-%d') AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_27_2
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 0 MONTH ) + INTERVAL 28 DAY , '%Y-%m-%d') AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_28_2
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 0 MONTH ) + INTERVAL 29 DAY , '%Y-%m-%d') AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_29_2
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 0 MONTH ) + INTERVAL 30 DAY , '%Y-%m-%d') AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_30_2
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 0 MONTH ) + INTERVAL 31 DAY , '%Y-%m-%d') AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_31_2


,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 1 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_01_3
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 2 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_02_3
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 3 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_03_3
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 4 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_04_3
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 5 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_05_3
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 6 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_06_3
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 7 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_07_3
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 8 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_08_3
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 9 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_09_3
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 10 DAY , '%Y-%m-%d') AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_10_3
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 11 DAY , '%Y-%m-%d') AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_11_3
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 12 DAY , '%Y-%m-%d') AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_12_3
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 13 DAY , '%Y-%m-%d') AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_13_3
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 14 DAY , '%Y-%m-%d') AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_14_3
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 15 DAY , '%Y-%m-%d') AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_15_3
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 16 DAY , '%Y-%m-%d') AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_16_3
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 17 DAY , '%Y-%m-%d') AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_17_3
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 18 DAY , '%Y-%m-%d') AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_18_3
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 19 DAY , '%Y-%m-%d') AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_19_3
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 20 DAY , '%Y-%m-%d') AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_20_3
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 21 DAY , '%Y-%m-%d') AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_21_3
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 22 DAY , '%Y-%m-%d') AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_22_3
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 23 DAY , '%Y-%m-%d') AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_23_3
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 24 DAY , '%Y-%m-%d') AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_24_3
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 25 DAY , '%Y-%m-%d') AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_25_3
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 26 DAY , '%Y-%m-%d') AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_26_3
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 27 DAY , '%Y-%m-%d') AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_27_3
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 28 DAY , '%Y-%m-%d') AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_28_3
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 29 DAY , '%Y-%m-%d') AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_29_3
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 30 DAY , '%Y-%m-%d') AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_30_3
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 31 DAY , '%Y-%m-%d') AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_31_3

,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 1 MONTH ) + INTERVAL 1 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_01_1
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 1 MONTH ) + INTERVAL 2 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_02_1
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 1 MONTH ) + INTERVAL 3 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_03_1
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 1 MONTH ) + INTERVAL 4 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_04_1
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 1 MONTH ) + INTERVAL 5 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_05_1
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 1 MONTH ) + INTERVAL 6 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_06_1
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 1 MONTH ) + INTERVAL 7 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_07_1
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 1 MONTH ) + INTERVAL 8 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_08_1
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 1 MONTH ) + INTERVAL 9 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_09_1
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 1 MONTH ) + INTERVAL 10 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 2 THEN DT.QTY END ),0) PL_10_1
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 1 MONTH ) + INTERVAL 11 DAY , '%Y-%m-%d') AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_11_1
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 1 MONTH ) + INTERVAL 12 DAY , '%Y-%m-%d') AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_12_1
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 1 MONTH ) + INTERVAL 13 DAY , '%Y-%m-%d') AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_13_1
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 1 MONTH ) + INTERVAL 14 DAY , '%Y-%m-%d') AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_14_1
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 1 MONTH ) + INTERVAL 15 DAY , '%Y-%m-%d') AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_15_1
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 1 MONTH ) + INTERVAL 16 DAY , '%Y-%m-%d') AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_16_1
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 1 MONTH ) + INTERVAL 17 DAY , '%Y-%m-%d') AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_17_1
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 1 MONTH ) + INTERVAL 18 DAY , '%Y-%m-%d') AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_18_1
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 1 MONTH ) + INTERVAL 19 DAY , '%Y-%m-%d') AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_19_1
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 1 MONTH ) + INTERVAL 20 DAY , '%Y-%m-%d') AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_20_1
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 1 MONTH ) + INTERVAL 21 DAY , '%Y-%m-%d') AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_21_1
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 1 MONTH ) + INTERVAL 22 DAY , '%Y-%m-%d') AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_22_1
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 1 MONTH ) + INTERVAL 23 DAY , '%Y-%m-%d') AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_23_1
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 1 MONTH ) + INTERVAL 24 DAY , '%Y-%m-%d') AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_24_1
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 1 MONTH ) + INTERVAL 25 DAY , '%Y-%m-%d') AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_25_1
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 1 MONTH ) + INTERVAL 26 DAY , '%Y-%m-%d') AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_26_1
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 1 MONTH ) + INTERVAL 27 DAY , '%Y-%m-%d') AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_27_1
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 1 MONTH ) + INTERVAL 28 DAY , '%Y-%m-%d') AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_28_1
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 1 MONTH ) + INTERVAL 29 DAY , '%Y-%m-%d') AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_29_1
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 1 MONTH ) + INTERVAL 30 DAY , '%Y-%m-%d') AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_30_1
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 1 MONTH ) + INTERVAL 31 DAY , '%Y-%m-%d') AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_31_1

,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 0 MONTH ) + INTERVAL 1 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_01_2
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 0 MONTH ) + INTERVAL 2 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_02_2
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 0 MONTH ) + INTERVAL 3 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_03_2
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 0 MONTH ) + INTERVAL 4 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_04_2
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 0 MONTH ) + INTERVAL 5 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_05_2
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 0 MONTH ) + INTERVAL 6 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_06_2
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 0 MONTH ) + INTERVAL 7 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_07_2
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 0 MONTH ) + INTERVAL 8 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_08_2
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 0 MONTH ) + INTERVAL 9 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_09_2
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 0 MONTH ) + INTERVAL 10 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 2 THEN DT.QTY END ),0) PL_10_2
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 0 MONTH ) + INTERVAL 11 DAY , '%Y-%m-%d') AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_11_2
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 0 MONTH ) + INTERVAL 12 DAY , '%Y-%m-%d') AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_12_2
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 0 MONTH ) + INTERVAL 13 DAY , '%Y-%m-%d') AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_13_2
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 0 MONTH ) + INTERVAL 14 DAY , '%Y-%m-%d') AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_14_2
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 0 MONTH ) + INTERVAL 15 DAY , '%Y-%m-%d') AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_15_2
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 0 MONTH ) + INTERVAL 16 DAY , '%Y-%m-%d') AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_16_2
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 0 MONTH ) + INTERVAL 17 DAY , '%Y-%m-%d') AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_17_2
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 0 MONTH ) + INTERVAL 18 DAY , '%Y-%m-%d') AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_18_2
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 0 MONTH ) + INTERVAL 19 DAY , '%Y-%m-%d') AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_19_2
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 0 MONTH ) + INTERVAL 20 DAY , '%Y-%m-%d') AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_20_2
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 0 MONTH ) + INTERVAL 21 DAY , '%Y-%m-%d') AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_21_2
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 0 MONTH ) + INTERVAL 22 DAY , '%Y-%m-%d') AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_22_2
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 0 MONTH ) + INTERVAL 23 DAY , '%Y-%m-%d') AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_23_2
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 0 MONTH ) + INTERVAL 24 DAY , '%Y-%m-%d') AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_24_2
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 0 MONTH ) + INTERVAL 25 DAY , '%Y-%m-%d') AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_25_2
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 0 MONTH ) + INTERVAL 26 DAY , '%Y-%m-%d') AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_26_2
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 0 MONTH ) + INTERVAL 27 DAY , '%Y-%m-%d') AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_27_2
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 0 MONTH ) + INTERVAL 28 DAY , '%Y-%m-%d') AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_28_2
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 0 MONTH ) + INTERVAL 29 DAY , '%Y-%m-%d') AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_29_2
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 0 MONTH ) + INTERVAL 30 DAY , '%Y-%m-%d') AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_30_2
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 0 MONTH ) + INTERVAL 31 DAY , '%Y-%m-%d') AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_31_2

,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 1 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_01_3
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 2 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_02_3
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 3 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_03_3
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 4 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_04_3
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 5 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_05_3
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 6 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_06_3
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 7 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_07_3
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 8 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_08_3
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 9 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_09_3
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 10 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 2 THEN DT.QTY END ),0) PL_10_3
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 11 DAY , '%Y-%m-%d') AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_11_3
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 12 DAY , '%Y-%m-%d') AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_12_3
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 13 DAY , '%Y-%m-%d') AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_13_3
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 14 DAY , '%Y-%m-%d') AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_14_3
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 15 DAY , '%Y-%m-%d') AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_15_3
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 16 DAY , '%Y-%m-%d') AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_16_3
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 17 DAY , '%Y-%m-%d') AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_17_3
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 18 DAY , '%Y-%m-%d') AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_18_3
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 19 DAY , '%Y-%m-%d') AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_19_3
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 20 DAY , '%Y-%m-%d') AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_20_3
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 21 DAY , '%Y-%m-%d') AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_21_3
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 22 DAY , '%Y-%m-%d') AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_22_3
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 23 DAY , '%Y-%m-%d') AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_23_3
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 24 DAY , '%Y-%m-%d') AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_24_3
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 25 DAY , '%Y-%m-%d') AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_25_3
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 26 DAY , '%Y-%m-%d') AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_26_3
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 27 DAY , '%Y-%m-%d') AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_27_3
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 28 DAY , '%Y-%m-%d') AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_28_3
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 29 DAY , '%Y-%m-%d') AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_29_3
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 30 DAY , '%Y-%m-%d') AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_30_3
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 31 DAY , '%Y-%m-%d') AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_31_3

,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 1 MONTH ) + INTERVAL 1 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_01_1
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 1 MONTH ) + INTERVAL 2 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_02_1
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 1 MONTH ) + INTERVAL 3 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_03_1
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 1 MONTH ) + INTERVAL 4 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_04_1
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 1 MONTH ) + INTERVAL 5 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_05_1
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 1 MONTH ) + INTERVAL 6 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_06_1
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 1 MONTH ) + INTERVAL 7 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_07_1
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 1 MONTH ) + INTERVAL 8 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_08_1
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 1 MONTH ) + INTERVAL 9 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_09_1
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 1 MONTH ) + INTERVAL 10 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 3 THEN DT.QTY END ),0) AC_10_1
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 1 MONTH ) + INTERVAL 11 DAY , '%Y-%m-%d') AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_11_1
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 1 MONTH ) + INTERVAL 12 DAY , '%Y-%m-%d') AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_12_1
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 1 MONTH ) + INTERVAL 13 DAY , '%Y-%m-%d') AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_13_1
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 1 MONTH ) + INTERVAL 14 DAY , '%Y-%m-%d') AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_14_1
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 1 MONTH ) + INTERVAL 15 DAY , '%Y-%m-%d') AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_15_1
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 1 MONTH ) + INTERVAL 16 DAY , '%Y-%m-%d') AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_16_1
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 1 MONTH ) + INTERVAL 17 DAY , '%Y-%m-%d') AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_17_1
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 1 MONTH ) + INTERVAL 18 DAY , '%Y-%m-%d') AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_18_1
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 1 MONTH ) + INTERVAL 19 DAY , '%Y-%m-%d') AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_19_1
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 1 MONTH ) + INTERVAL 20 DAY , '%Y-%m-%d') AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_20_1
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 1 MONTH ) + INTERVAL 21 DAY , '%Y-%m-%d') AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_21_1
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 1 MONTH ) + INTERVAL 22 DAY , '%Y-%m-%d') AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_22_1
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 1 MONTH ) + INTERVAL 23 DAY , '%Y-%m-%d') AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_23_1
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 1 MONTH ) + INTERVAL 24 DAY , '%Y-%m-%d') AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_24_1
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 1 MONTH ) + INTERVAL 25 DAY , '%Y-%m-%d') AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_25_1
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 1 MONTH ) + INTERVAL 26 DAY , '%Y-%m-%d') AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_26_1
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 1 MONTH ) + INTERVAL 27 DAY , '%Y-%m-%d') AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_27_1
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 1 MONTH ) + INTERVAL 28 DAY , '%Y-%m-%d') AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_28_1
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 1 MONTH ) + INTERVAL 29 DAY , '%Y-%m-%d') AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_29_1
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 1 MONTH ) + INTERVAL 30 DAY , '%Y-%m-%d') AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_30_1
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 1 MONTH ) + INTERVAL 31 DAY , '%Y-%m-%d') AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_31_1

,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 0 MONTH ) + INTERVAL 1 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_01_2
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 0 MONTH ) + INTERVAL 2 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_02_2
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 0 MONTH ) + INTERVAL 3 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_03_2
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 0 MONTH ) + INTERVAL 4 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_04_2
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 0 MONTH ) + INTERVAL 5 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_05_2
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 0 MONTH ) + INTERVAL 6 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_06_2
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 0 MONTH ) + INTERVAL 7 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_07_2
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 0 MONTH ) + INTERVAL 8 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_08_2
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 0 MONTH ) + INTERVAL 9 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_09_2
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 0 MONTH ) + INTERVAL 10 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 3 THEN DT.QTY END ),0) AC_10_2
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 0 MONTH ) + INTERVAL 11 DAY , '%Y-%m-%d') AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_11_2
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 0 MONTH ) + INTERVAL 12 DAY , '%Y-%m-%d') AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_12_2
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 0 MONTH ) + INTERVAL 13 DAY , '%Y-%m-%d') AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_13_2
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 0 MONTH ) + INTERVAL 14 DAY , '%Y-%m-%d') AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_14_2
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 0 MONTH ) + INTERVAL 15 DAY , '%Y-%m-%d') AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_15_2
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 0 MONTH ) + INTERVAL 16 DAY , '%Y-%m-%d') AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_16_2
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 0 MONTH ) + INTERVAL 17 DAY , '%Y-%m-%d') AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_17_2
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 0 MONTH ) + INTERVAL 18 DAY , '%Y-%m-%d') AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_18_2
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 0 MONTH ) + INTERVAL 19 DAY , '%Y-%m-%d') AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_19_2
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 0 MONTH ) + INTERVAL 20 DAY , '%Y-%m-%d') AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_20_2
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 0 MONTH ) + INTERVAL 21 DAY , '%Y-%m-%d') AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_21_2
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 0 MONTH ) + INTERVAL 22 DAY , '%Y-%m-%d') AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_22_2
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 0 MONTH ) + INTERVAL 23 DAY , '%Y-%m-%d') AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_23_2
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 0 MONTH ) + INTERVAL 24 DAY , '%Y-%m-%d') AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_24_2
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 0 MONTH ) + INTERVAL 25 DAY , '%Y-%m-%d') AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_25_2
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 0 MONTH ) + INTERVAL 26 DAY , '%Y-%m-%d') AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_26_2
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 0 MONTH ) + INTERVAL 27 DAY , '%Y-%m-%d') AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_27_2
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 0 MONTH ) + INTERVAL 28 DAY , '%Y-%m-%d') AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_28_2
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 0 MONTH ) + INTERVAL 29 DAY , '%Y-%m-%d') AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_29_2
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 0 MONTH ) + INTERVAL 30 DAY , '%Y-%m-%d') AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_30_2
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() - INTERVAL 0 MONTH ) + INTERVAL 31 DAY , '%Y-%m-%d') AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_31_2

,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 1 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_01_3
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 2 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_02_3
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 3 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_03_3
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 4 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_04_3
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 5 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_05_3
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 6 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_06_3
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 7 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_07_3
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 8 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_08_3
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 9 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_09_3
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 10 DAY , '%Y-%m-%d') AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_10_3
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 11 DAY , '%Y-%m-%d') AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_11_3
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 12 DAY , '%Y-%m-%d') AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_12_3
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 13 DAY , '%Y-%m-%d') AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_13_3
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 14 DAY , '%Y-%m-%d') AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_14_3
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 15 DAY , '%Y-%m-%d') AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_15_3
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 16 DAY , '%Y-%m-%d') AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_16_3
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 17 DAY , '%Y-%m-%d') AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_17_3
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 18 DAY , '%Y-%m-%d') AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_18_3
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 19 DAY , '%Y-%m-%d') AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_19_3
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 20 DAY , '%Y-%m-%d') AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_20_3
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 21 DAY , '%Y-%m-%d') AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_21_3
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 22 DAY , '%Y-%m-%d') AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_22_3
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 23 DAY , '%Y-%m-%d') AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_23_3
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 24 DAY , '%Y-%m-%d') AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_24_3
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 25 DAY , '%Y-%m-%d') AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_25_3
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 26 DAY , '%Y-%m-%d') AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_26_3
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 27 DAY , '%Y-%m-%d') AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_27_3
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 28 DAY , '%Y-%m-%d') AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_28_3
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 29 DAY , '%Y-%m-%d') AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_29_3
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 30 DAY , '%Y-%m-%d') AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_30_3
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 31 DAY , '%Y-%m-%d') AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_31_3
FROM 

TEMP_DEMAND_DATA DT

GROUP BY 
 DT.PLANT_CD
,DT.PARENT_SEC_CD
,DT.SOURCE_CD
,DT.SOURCE_NAME
,DT.ITEM_CD
,DT.ITEM_NAME
,DT.DM_TYP
,DT.SNP
,DT.LCT
) DT


GROUP BY 
 DT.PLANT_CD
,DT.PARENT_SEC_CD
,DT.SOURCE_CD
,DT.SOURCE_NAME
,DT.ITEM_CD
,DT.ITEM_NAME
,DT.SNP
,DT.LCT