
SELECT
 DT.PLANT_CD
,DT.PARENT_SEC_CD
,DT.SOURCE_CD
,DT.SOURCE_NAME
,DT.ITEM_CD
,DT.ITEM_NAME
,DT.MODEL
,DT.SNP
,DT.LCT
,IFNULL(SUM( DT.DM_01 ),0)  DM_01
,IFNULL(SUM( DT.DM_02 ),0)  DM_02
,IFNULL(SUM( DT.DM_03 ),0)  DM_03
,IFNULL(SUM( DT.DM_04 ),0)  DM_04
,IFNULL(SUM( DT.DM_05 ),0)  DM_05
,IFNULL(SUM( DT.DM_06 ),0)  DM_06
,IFNULL(SUM( DT.DM_07 ),0)  DM_07
,IFNULL(SUM( DT.DM_08 ),0)  DM_08
,IFNULL(SUM( DT.DM_09 ),0)  DM_09
,IFNULL(SUM( DT.DM_10 ),0)  DM_10
,IFNULL(SUM( DT.DM_11 ),0)  DM_11
,IFNULL(SUM( DT.DM_12 ),0)  DM_12
,IFNULL(SUM( DT.DM_13 ),0)  DM_13
,IFNULL(SUM( DT.DM_14 ),0)  DM_14
,IFNULL(SUM( DT.DM_15 ),0)  DM_15
,IFNULL(SUM( DT.DM_16 ),0)  DM_16
,IFNULL(SUM( DT.DM_17 ),0)  DM_17
,IFNULL(SUM( DT.DM_18 ),0)  DM_18
,IFNULL(SUM( DT.DM_19 ),0)  DM_19
,IFNULL(SUM( DT.DM_20 ),0)  DM_20
,IFNULL(SUM( DT.DM_21 ),0)  DM_21
,IFNULL(SUM( DT.DM_22 ),0)  DM_22
,IFNULL(SUM( DT.DM_23 ),0)  DM_23
,IFNULL(SUM( DT.DM_24 ),0)  DM_24
,IFNULL(SUM( DT.DM_25 ),0)  DM_25
,IFNULL(SUM( DT.DM_26 ),0)  DM_26
,IFNULL(SUM( DT.DM_27 ),0)  DM_27
,IFNULL(SUM( DT.DM_28 ),0)  DM_28
,IFNULL(SUM( DT.DM_29 ),0)  DM_29
,IFNULL(SUM( DT.DM_30 ),0)  DM_30
,IFNULL(SUM( DT.DM_31 ),0)  DM_31

,IFNULL(SUM( DT.PL_01 ),0)  PL_01
,IFNULL(SUM( DT.PL_02 ),0)  PL_02
,IFNULL(SUM( DT.PL_03 ),0)  PL_03
,IFNULL(SUM( DT.PL_04 ),0)  PL_04
,IFNULL(SUM( DT.PL_05 ),0)  PL_05
,IFNULL(SUM( DT.PL_06 ),0)  PL_06
,IFNULL(SUM( DT.PL_07 ),0)  PL_07
,IFNULL(SUM( DT.PL_08 ),0)  PL_08
,IFNULL(SUM( DT.PL_09 ),0)  PL_09
,IFNULL(SUM( DT.PL_10 ),0)  PL_10
,IFNULL(SUM( DT.PL_11 ),0)  PL_11
,IFNULL(SUM( DT.PL_12 ),0)  PL_12
,IFNULL(SUM( DT.PL_13 ),0)  PL_13
,IFNULL(SUM( DT.PL_14 ),0)  PL_14
,IFNULL(SUM( DT.PL_15 ),0)  PL_15
,IFNULL(SUM( DT.PL_16 ),0)  PL_16
,IFNULL(SUM( DT.PL_17 ),0)  PL_17
,IFNULL(SUM( DT.PL_18 ),0)  PL_18
,IFNULL(SUM( DT.PL_19 ),0)  PL_19
,IFNULL(SUM( DT.PL_20 ),0)  PL_20
,IFNULL(SUM( DT.PL_21 ),0)  PL_21
,IFNULL(SUM( DT.PL_22 ),0)  PL_22
,IFNULL(SUM( DT.PL_23 ),0)  PL_23
,IFNULL(SUM( DT.PL_24 ),0)  PL_24
,IFNULL(SUM( DT.PL_25 ),0)  PL_25
,IFNULL(SUM( DT.PL_26 ),0)  PL_26
,IFNULL(SUM( DT.PL_27 ),0)  PL_27
,IFNULL(SUM( DT.PL_28 ),0)  PL_28
,IFNULL(SUM( DT.PL_29 ),0)  PL_29
,IFNULL(SUM( DT.PL_30 ),0)  PL_30
,IFNULL(SUM( DT.PL_31 ),0)  PL_31

,IFNULL(SUM( DT.AC_01 ),0)  AC_01
,IFNULL(SUM( DT.AC_02 ),0)  AC_02
,IFNULL(SUM( DT.AC_03 ),0)  AC_03
,IFNULL(SUM( DT.AC_04 ),0)  AC_04
,IFNULL(SUM( DT.AC_05 ),0)  AC_05
,IFNULL(SUM( DT.AC_06 ),0)  AC_06
,IFNULL(SUM( DT.AC_07 ),0)  AC_07
,IFNULL(SUM( DT.AC_08 ),0)  AC_08
,IFNULL(SUM( DT.AC_09 ),0)  AC_09
,IFNULL(SUM( DT.AC_10 ),0)  AC_10
,IFNULL(SUM( DT.AC_11 ),0)  AC_11
,IFNULL(SUM( DT.AC_12 ),0)  AC_12
,IFNULL(SUM( DT.AC_13 ),0)  AC_13
,IFNULL(SUM( DT.AC_14 ),0)  AC_14
,IFNULL(SUM( DT.AC_15 ),0)  AC_15
,IFNULL(SUM( DT.AC_16 ),0)  AC_16
,IFNULL(SUM( DT.AC_17 ),0)  AC_17
,IFNULL(SUM( DT.AC_18 ),0)  AC_18
,IFNULL(SUM( DT.AC_19 ),0)  AC_19
,IFNULL(SUM( DT.AC_20 ),0)  AC_20
,IFNULL(SUM( DT.AC_21 ),0)  AC_21
,IFNULL(SUM( DT.AC_22 ),0)  AC_22
,IFNULL(SUM( DT.AC_23 ),0)  AC_23
,IFNULL(SUM( DT.AC_24 ),0)  AC_24
,IFNULL(SUM( DT.AC_25 ),0)  AC_25
,IFNULL(SUM( DT.AC_26 ),0)  AC_26
,IFNULL(SUM( DT.AC_27 ),0)  AC_27
,IFNULL(SUM( DT.AC_28 ),0)  AC_28
,IFNULL(SUM( DT.AC_29 ),0)  AC_29
,IFNULL(SUM( DT.AC_30 ),0)  AC_30
,IFNULL(SUM( DT.AC_31 ),0)  AC_31


FROM
(
SELECT

 DT.PLANT_CD
,DT.PARENT_SEC_CD
,DT.SOURCE_CD
,DT.SOURCE_NAME
,DT.ITEM_CD
,DT.ITEM_NAME
,DT.MODEL
,DT.SNP
,DT.LCT
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 1 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_01
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 2 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_02
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 3 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_03
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 4 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_04
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 5 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_05
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 6 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_06
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 7 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_07
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 8 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_08
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 9 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_09
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 10 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_10
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 11 DAY , '%Y-%m-%d') AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_11
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 12 DAY , '%Y-%m-%d') AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_12
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 13 DAY , '%Y-%m-%d') AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_13
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 14 DAY , '%Y-%m-%d') AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_14
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 15 DAY , '%Y-%m-%d') AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_15
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 16 DAY , '%Y-%m-%d') AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_16
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 17 DAY , '%Y-%m-%d') AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_17
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 18 DAY , '%Y-%m-%d') AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_18
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 19 DAY , '%Y-%m-%d') AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_19
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 20 DAY , '%Y-%m-%d') AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_20
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 21 DAY , '%Y-%m-%d') AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_21
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 22 DAY , '%Y-%m-%d') AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_22
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 23 DAY , '%Y-%m-%d') AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_23
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 24 DAY , '%Y-%m-%d') AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_24
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 25 DAY , '%Y-%m-%d') AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_25
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 26 DAY , '%Y-%m-%d') AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_26
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 27 DAY , '%Y-%m-%d') AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_27
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 28 DAY , '%Y-%m-%d') AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_28
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 29 DAY , '%Y-%m-%d') AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_29
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 30 DAY , '%Y-%m-%d') AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_30
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 31 DAY , '%Y-%m-%d') AND DT.DM_TYP = 1 THEN DT.QTY END ),0)  DM_31

,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 1 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_01
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 2 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_02
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 3 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_03
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 4 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_04
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 5 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_05
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 6 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_06
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 7 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_07
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 8 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_08
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 9 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_09
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 10 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_10
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 11 DAY , '%Y-%m-%d') AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_11
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 12 DAY , '%Y-%m-%d') AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_12
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 13 DAY , '%Y-%m-%d') AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_13
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 14 DAY , '%Y-%m-%d') AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_14
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 15 DAY , '%Y-%m-%d') AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_15
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 16 DAY , '%Y-%m-%d') AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_16
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 17 DAY , '%Y-%m-%d') AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_17
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 18 DAY , '%Y-%m-%d') AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_18
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 19 DAY , '%Y-%m-%d') AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_19
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 20 DAY , '%Y-%m-%d') AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_20
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 21 DAY , '%Y-%m-%d') AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_21
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 22 DAY , '%Y-%m-%d') AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_22
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 23 DAY , '%Y-%m-%d') AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_23
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 24 DAY , '%Y-%m-%d') AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_24
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 25 DAY , '%Y-%m-%d') AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_25
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 26 DAY , '%Y-%m-%d') AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_26
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 27 DAY , '%Y-%m-%d') AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_27
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 28 DAY , '%Y-%m-%d') AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_28
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 29 DAY , '%Y-%m-%d') AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_29
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 30 DAY , '%Y-%m-%d') AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_30
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 31 DAY , '%Y-%m-%d') AND DT.DM_TYP = 2 THEN DT.QTY END ),0)  PL_31

,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 1 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_01
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 2 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_02
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 3 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_03
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 4 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_04
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 5 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_05
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 6 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_06
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 7 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_07
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 8 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_08
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 9 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_09
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 10 DAY , '%Y-%m-%d')  AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_10
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 11 DAY , '%Y-%m-%d') AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_11
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 12 DAY , '%Y-%m-%d') AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_12
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 13 DAY , '%Y-%m-%d') AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_13
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 14 DAY , '%Y-%m-%d') AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_14
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 15 DAY , '%Y-%m-%d') AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_15
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 16 DAY , '%Y-%m-%d') AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_16
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 17 DAY , '%Y-%m-%d') AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_17
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 18 DAY , '%Y-%m-%d') AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_18
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 19 DAY , '%Y-%m-%d') AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_19
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 20 DAY , '%Y-%m-%d') AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_20
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 21 DAY , '%Y-%m-%d') AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_21
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 22 DAY , '%Y-%m-%d') AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_22
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 23 DAY , '%Y-%m-%d') AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_23
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 24 DAY , '%Y-%m-%d') AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_24
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 25 DAY , '%Y-%m-%d') AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_25
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 26 DAY , '%Y-%m-%d') AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_26
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 27 DAY , '%Y-%m-%d') AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_27
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 28 DAY , '%Y-%m-%d') AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_28
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 29 DAY , '%Y-%m-%d') AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_29
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 30 DAY , '%Y-%m-%d') AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_30
,IFNULL(SUM( CASE WHEN DATE_FORMAT(DT.ADATE,'%Y-%m-%d') = DATE_FORMAT( LAST_DAY( CURDATE() + INTERVAL 1 MONTH ) + INTERVAL 31 DAY , '%Y-%m-%d') AND DT.DM_TYP = 3 THEN DT.QTY END ),0)  AC_31
FROM 

DEMAND_DATA DT

GROUP BY 
 DT.PLANT_CD
,DT.PARENT_SEC_CD
,DT.SOURCE_CD
,DT.SOURCE_NAME
,DT.ITEM_CD
,DT.ITEM_NAME
,DT.DM_TYP
,DT.SNP
,DT.LCT
) DT


GROUP BY 
 DT.PLANT_CD
,DT.PARENT_SEC_CD
,DT.SOURCE_CD
,DT.SOURCE_NAME
,DT.ITEM_CD
,DT.ITEM_NAME
,DT.SNP
,DT.LCT